name: cicd deploy spring angular avec github action

on:
  push:
    branches: main
jobs:
  buid_and_deploy:
    runs_on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v7